const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 2,
      ownRating: 1,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: true,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: true,
      isCompare: true,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      ownRating: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: true,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      ownRating: 4,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Modern Chair 1',
      name: 'Modern Chair 1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Modern Chair 2',
      name: 'Modern Chair 2',
      category: 'chair',
      price: 10,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },

    {
      id: 'Old-fashioned chair 3',
      name: 'Old-fashioned chair 3',
      category: 'chair',
      price: 50,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Modern Chair 4',
      name: 'Modern Chair 4',
      category: 'chair',
      price: 10,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Modern Chair 5',
      name: 'Modern Chair 5',
      category: 'chair',
      price: 15,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Modern Chair 6',
      name: 'Modern Chair 6',
      category: 'chair',
      price: 5,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Modern Chair 7',
      name: 'Modern Chair 7',
      category: 'chair',
      price: 5,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },

    {
      id: 'Modern Chair 8',
      name: 'Modern Chair 8',
      category: 'chair',
      price: 5,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Modern Chair 9',
      name: 'Modern Chair 9',
      category: 'chair',
      price: 5,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },

    {
      id: 'Cosy modern sofa 1',
      name: 'Cosy modern sofa 1',
      category: 'sofa',
      price: 20,
      stars: 4,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Cosy modern sofa 2',
      name: 'Cosy modern sofa 2',
      category: 'sofa',
      price: 25,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Cosy modern sofa 3',
      name: 'Cosy modern sofa 3',
      category: 'sofa',
      price: 25,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Cosy modern sofa 4',
      name: 'Cosy modern sofa 4',
      category: 'sofa',
      price: 25,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Cosy modern sofa 5',
      name: 'Cosy modern sofa 5',
      category: 'sofa',
      price: 25,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Cosy modern sofa 6',
      name: 'Cosy modern sofa 6',
      category: 'sofa',
      price: 25,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'cosy modern sofa 7',
      name: 'cosy modern sofa 7',
      category: 'sofa',
      price: 25,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Cosy modern sofa 8',
      name: 'Cosy modern sofa 8',
      category: 'sofa',
      price: 25,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
    {
      id: 'Cosy modern sofa 9',
      name: 'Cosy modern sofa 9',
      category: 'sofa',
      price: 25,
      stars: 5,
      promo: 'sale',
      newFurniture: true,
      isFavorite: false,
      isCompare: false,
    },
  ],

  cart: {
    products: [],
  },
  brands: [
    {
      id: 1,
      description: '',
      url: 'images/brands/brands1.jpg',
    },
    {
      id: 2,
      description: '',
      url: 'images/brands/brands2.jpg',
    },
    {
      id: 3,
      description: '',
      url: 'images/brands/brands3.jpg',
    },
    {
      id: 4,
      description: '',
      url: 'images/brands/brands4.jpg',
    },
    {
      id: 5,
      description: '',
      url: 'images/brands/brands5.jpg',
    },
    {
      id: 6,
      description: '',
      url: 'images/brands/brands6.jpg',
    },
  ],
};

export default initialState;
